# fly.toml app configuration file generated for deepfield on 2026-06-29T08:01:37Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'deepfield'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile'

[env]
  DEEPFIELD_ENV = 'production'
  DEEPFIELD_FREE_DEEP_RUNS = '3'
  DEEPFIELD_GLOBAL_DAILY_DEEP_RUNS = '50'
  PORT = '8000'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
